- 설치
    - GPU가 있는 경우 
        - conda install keras-gpu
        - conda install tensorflow_gpu(텐서플로우 경우)
    - 일반적인 경우
        - conda install keras

- keras는 API기반 인터페이스이다
- 엔진을 교체하고 싶다면
    - 사용자계정/.keras/keras.json
    {
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "tensorflow",   <-- 사용 엔진 ( 프레임웍 )
    "image_data_format": "channels_last"
}

In [6]:
import keras

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\dtyp

### 간단한 루틴으로 케라스 확인

In [1]:
import numpy as np

In [2]:
# 더미 데이터 구성
x = np.array( [0,1,2,3,4] )

In [3]:
# 2는 가중치
# 1은 편향
y = x * 2 + 1

In [4]:
x, y

(array([0, 1, 2, 3, 4]), array([1, 3, 5, 7, 9]))

In [7]:
# 인공 신경말 모델링
# 인공 신경망을 만들기 시작했음을 알린다. (파이썬 프로세스에게)
model = keras.models.Sequential()

# add() 함수를 이용하여 인공지능 계층(layer)를 추가
# 추가된 계층은 입력노드와 가중치 등을 가지는 선형 처리 계층이다.
model.add( keras.layers.Dense(1, input_shape=(1,  ) ) ) # keras.layers.Dense() : 층을 하나 만드는 것이다

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
# 모델 학습 -> [최적화 알고리즘 : SGD ], [손실함수 평균제곱근오차 : mse]
model.compile('SGD','mse')

In [9]:
# 훈련
# epochs : 인공신경망 학습시 학습 데이터 전체가 사용된 한세대, 반복횟수, 세대수
# verbose : 학습 진행 사항의 표시, 0 : 이면 표시하지 않는다
model.fit( x[:2], y[:2], epochs=1000, verbose=0 ) # 1000세대를 학습해라 

Instructions for updating:
Use tf.cast instead.


In [10]:
# 예측
model.predict(x[2:]).flatten()

array([4.9683247, 6.945405 , 8.922484 ], dtype=float32)

In [11]:
# 실제값 
y[2:] 

array([5, 7, 9])